name: cached_video_player_plus
description: "The video_player plugin that went to therapy, worked on its commitment issues, and now actually remembers your videos!"
version: 4.2.2
homepage: https://outdatedguy.rocks
repository: https://github.com/OutdatedGuy/cached_video_player_plus
topics:
  - caching
  - video-caching
  - video
  - video-player
funding:
  - https://buymeacoffee.com/outdatedguy
  - https://github.com/sponsors/OutdatedGuy
screenshots:
  - description: "A sleek, futuristic video player, designed for seamless streaming and robust caching performance. Experience cutting-edge visuals and uninterrupted playback."
    path: screenshots/thumbnail.png
  - description: "Example of Basic Video Playback on Android."
    path: screenshots/Android-Basic-Playback.webp
  - description: "Example of Chewie Integration on iOS."
    path: screenshots/iOS-Chewie-Integration.webp
  - description: "Example of Pre-Caching on macOS."
    path: screenshots/macOS-Pre-Caching.webp
  - description: "Example of Advance Cache Management on Windows."
    path: screenshots/Windows-Advance-Cache-Management.webp

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  http: ^1.6.0
  video_player: ^2.10.1
  video_player_platform_interface: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: CachedVideoPlayerPlusPlugin
      android:
        package: com.example.cached_video_player_plus
        pluginClass: CachedVideoPlayerPlusPlugin

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
