name: http_cache_stream
description: "Simultaneously download, cache, and stream remote content. Perfect for media players and any plugin that streams web content."
version: 0.0.4
homepage: https://github.com/Colton127/http_cache_stream
repository: https://github.com/Colton127/http_cache_stream
topics:
  - cache
  - streaming
  - video
  - audio
  - http

platforms:
  android:
  ios:
  linux:
  macos:
  windows:


environment:
  sdk: ^3.5.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  crypto: ^3.0.6
  http: ^1.3.0
  path: ^1.9.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
